
GET  http://localhost:8080/api/product/get
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYm9va2luZyB3ZWJzaXRlIiwiaXNzIjoibXkgd2Vic2l0ZS5jb20iLCJpYXQiOjE2ODQyMjE3ODEsImV4cCI6MTY4NDI1MDU4MSwiYXVkIjoiNjQ2MmZlMDg0YTA1Yjk3MzllNzQzZGI0In0.H4c67irB_nniJ3sFL_MwLQCA4Kh-EcYEApEOt3G7T58


###
POST  http://localhost:8080/api/product/post
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYm9va2luZyB3ZWJzaXRlIiwiaXNzIjoibXkgd2Vic2l0ZS5jb20iLCJpYXQiOjE2ODQyODcyMTcsImV4cCI6MTY4NDMxOTYxNywiYXVkIjoiNjQ2MmZlMDg0YTA1Yjk3MzllNzQzZGI0In0.uRwXr9StmZzPbiNKooPrZ8tya4VV4UKO35ekIFU0GA0


###
POST  http://localhost:8080/auth/login
Content-Type: application/json

{
    "email":"dhoni111@gmail.com",
    "password":"Dhoni@111"
}


###
POST  http://localhost:8080/auth/register
Content-Type: application/json 

{
    "email":"mugesh123@gmail.com",
    "password":"Dhoni@111",
    "firstname":"singh kartar",
    "lastname":"m",
    "state":"punjabi",
    "city":"haryanavi",
    "street":"dholkpura",
    "zipcode":"600019"

}

###
POST http://localhost:8080/auth/adminregister
Content-Type: application/json

{
    "email":"nisha2@gmail18000.com",
    "password":"Nisha@111"
}

###
POST http://localhost:8080/auth/adminlogin
Content-Type: application/json

{
    "email":"nisha2@gmail.com",
    "password":"Nisha@111"
}




###

POST  http://localhost:8080/auth/refresh-token
Content-Type: application/json

{
    "refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2ODA1ODk4OTksImV4cCI6MTcxMjE0NzQ5OSwiYXVkIjoiNjQyYmMzMTUyMWM5N2ZiOGYwOTg5OWNiIiwiaXNzIjoibXkgd2Vic2l0ZS5jb20ifQ.tjQNGqbVb_NNZ8aMIilS9QxJHsoefM1kr9zJ1qJLs1U"
}


###

POST  http://localhost:8080/main/mainpost
Content-Type: application/json

{
    "para":"chennai hotel its",
    "image":"chennai2.2.jpg",
    "title":"new hotel"
}


###
DELETE  http://localhost:8080/auth/logout
Content-Type: application/json

{
    "refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2ODA3NjQwMDUsImV4cCI6MTcxMjMyMTYwNSwiYXVkIjoiNjQyY2VjNjFlZWU0MmVlOTQ4MmQ2YWZmIiwiaXNzIjoibXkgd2Vic2l0ZS5jb20ifQ.UcoEi4hvy9YaZ3ZoMmTvChrlzN_Io3m8rTAzMyZQy9g"

}